# OUH Document Build task (Direct CI) - OUH-Hugo: Updated 16-07-2024. v3.2.0
pages:
  image: $CI_REGISTRY/www/pages-ouh-hugo:6c90e207
  stage: deploy
  tags: ["pages"]

  before_script:
    # - ls -la /pre-docs
    - mv /pre-docs/node_modules docs/
    - cd docs/
    # - ls -la
    # - npm install -D autoprefixer postcss-cli postcss  # Needed for Docsy build in local dir
    # - pwd  # Confirm expected build location
    # - hugo env  # Confirm expected build environment

  script:
    - export HUGO_CACHEDIR="/pre-docs/cache/hugo"
    - echo "Pre-build Cache"
    - du -s $HUGO_CACHEDIR
    - hugo --minify --gc --templateMetrics --logLevel debug --ignoreCache
    - echo "Post-build Cache"
    - du -s $HUGO_CACHEDIR

  after_script:
    # - pwd
    # - ls -la
    - /usr/local/bin/pagefind --site "public"

  artifacts:
    paths:
    - public
    expire_in: 20 mins

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # EDIT ME for your project's published branch, typically "main"
